# This workflow will install Python dependencies, run tests and lint
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v4.1.1
      - name: Set up Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgirepository1.0-dev
          python -m pip install --upgrade pip
          pip install -e .[server]
          pip install -e .[test]
      - name: Lint/test with pre-commit
        run: |
          mypy --version
          which mypy
          which pre-commit
          pre-commit --version
          pwd
          ls -la
          export
          SKIP=no-commit-to-branch pre-commit run --all-files -v --hook-stage post-merge
          echo "Running mypy manually again!"
          mypy -v matter_server/server/device_controller.py
          mypy -v --no-incremental matter_server/server/device_controller.py
      - name: Lint/test with pre-commit 2
        uses: pre-commit/action@v3.0.1

  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.11"
          - "3.12"

    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v4.1.1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgirepository1.0-dev
          python -m pip install --upgrade pip
          pip install -e .[server]
          pip install -e .[test]
      - name: Pytest
        run: pytest --durations 10 --cov-report term-missing --cov=matter_server --cov-report=xml tests/
